---
plugins:
  - babel
  - jest

env:
  node: true
  browser: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'prettier'

rules:
  no-console: 0
  arrow-parens: ['error', 'always']
